Traceback (most recent call last):
  File "/Users/aapetty/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/aapetty/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aapetty/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/aapetty/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/aapetty/opt/anaconda3/envs/icesat2_book/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/aapetty/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/Users/aapetty/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/aapetty/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Maps of the means 
t2m_winter_means = compute_gridcell_winter_means(book_ds.t2m, years=years)
pl = staticArcticMaps(t2m_winter_means, title="Winter mean 2 meter tempertaure", cmap="coolwarm", vmin=-40, vmax=-15)
display(pl)

# Mean monthly lineplot
static_winter_comparison_lineplot(book_ds.t2m, years=years,  figsize=(5,3), save_label=save_label, legend=True)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/var/folders/2x/8476fbt56qd5m2b5vgkbz2qm0000gp/T/ipykernel_47416/255254877.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# Maps of the means[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mt2m_winter_means[0m [0;34m=[0m [0mcompute_gridcell_winter_means[0m[0;34m([0m[0mbook_ds[0m[0;34m.[0m[0mt2m[0m[0;34m,[0m [0myears[0m[0;34m=[0m[0myears[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mpl[0m [0;34m=[0m [0mstaticArcticMaps[0m[0;34m([0m[0mt2m_winter_means[0m[0;34m,[0m [0mtitle[0m[0;34m=[0m[0;34m"Winter mean 2 meter tempertaure"[0m[0;34m,[0m [0mcmap[0m[0;34m=[0m[0;34m"coolwarm"[0m[0;34m,[0m [0mvmin[0m[0;34m=[0m[0;34m-[0m[0;36m40[0m[0;34m,[0m [0mvmax[0m[0;34m=[0m[0;34m-[0m[0;36m15[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0mdisplay[0m[0;34m([0m[0mpl[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;32m~/GitHub/akpetty/icesat2-book/content/utils/plotting_utils.py[0m in [0;36mstaticArcticMaps[0;34m(da, title, out_str, cmap, col, col_wrap, vmin, vmax, set_cbarlabel, min_lat, savefig)[0m
[1;32m    169[0m     [0;31m# save figure[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    170[0m     [0;32mif[0m [0msavefig[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 171[0;31m         [0mplt[0m[0;34m.[0m[0msavefig[0m[0;34m([0m[0;34m'./figs/maps_'[0m[0;34m+[0m[0mout_str[0m[0;34m+[0m[0;34m'.png'[0m[0;34m,[0m [0mdpi[0m[0;34m=[0m[0;36m400[0m[0;34m,[0m [0mfacecolor[0m[0;34m=[0m[0;34m"white"[0m[0;34m,[0m [0mbbox_inches[0m[0;34m=[0m[0;34m'tight'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    172[0m [0;34m[0m[0m
[1;32m    173[0m     [0mplt[0m[0;34m.[0m[0mclose[0m[0;34m([0m[0;34m)[0m [0;31m# Close so it doesnt automatically display in notebook[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/matplotlib/pyplot.py[0m in [0;36msavefig[0;34m(*args, **kwargs)[0m
[1;32m    964[0m [0;32mdef[0m [0msavefig[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    965[0m     [0mfig[0m [0;34m=[0m [0mgcf[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 966[0;31m     [0mres[0m [0;34m=[0m [0mfig[0m[0;34m.[0m[0msavefig[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    967[0m     [0mfig[0m[0;34m.[0m[0mcanvas[0m[0;34m.[0m[0mdraw_idle[0m[0;34m([0m[0;34m)[0m   [0;31m# need this if 'transparent=True' to reset colors[0m[0;34m[0m[0;34m[0m[0m
[1;32m    968[0m     [0;32mreturn[0m [0mres[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/matplotlib/figure.py[0m in [0;36msavefig[0;34m(self, fname, transparent, **kwargs)[0m
[1;32m   3013[0m                 [0mpatch[0m[0;34m.[0m[0mset_edgecolor[0m[0;34m([0m[0;34m'none'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3014[0m [0;34m[0m[0m
[0;32m-> 3015[0;31m         [0mself[0m[0;34m.[0m[0mcanvas[0m[0;34m.[0m[0mprint_figure[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3016[0m [0;34m[0m[0m
[1;32m   3017[0m         [0;32mif[0m [0mtransparent[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/matplotlib/backend_bases.py[0m in [0;36mprint_figure[0;34m(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)[0m
[1;32m   2253[0m                 [0;31m# force the figure dpi to 72), so we need to set it again here.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2254[0m                 [0;32mwith[0m [0mcbook[0m[0;34m.[0m[0m_setattr_cm[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mfigure[0m[0;34m,[0m [0mdpi[0m[0;34m=[0m[0mdpi[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2255[0;31m                     result = print_method(
[0m[1;32m   2256[0m                         [0mfilename[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2257[0m                         [0mfacecolor[0m[0;34m=[0m[0mfacecolor[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/matplotlib/backend_bases.py[0m in [0;36mwrapper[0;34m(*args, **kwargs)[0m
[1;32m   1667[0m             [0mkwargs[0m[0;34m.[0m[0mpop[0m[0;34m([0m[0marg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1668[0m [0;34m[0m[0m
[0;32m-> 1669[0;31m         [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1670[0m [0;34m[0m[0m
[1;32m   1671[0m     [0;32mreturn[0m [0mwrapper[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py[0m in [0;36mprint_png[0;34m(self, filename_or_obj, metadata, pil_kwargs, *args)[0m
[1;32m    507[0m         """
[1;32m    508[0m         [0mFigureCanvasAgg[0m[0;34m.[0m[0mdraw[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 509[0;31m         mpl.image.imsave(
[0m[1;32m    510[0m             [0mfilename_or_obj[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mbuffer_rgba[0m[0;34m([0m[0;34m)[0m[0;34m,[0m [0mformat[0m[0;34m=[0m[0;34m"png"[0m[0;34m,[0m [0morigin[0m[0;34m=[0m[0;34m"upper"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    511[0m             dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)

[0;32m~/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/matplotlib/image.py[0m in [0;36mimsave[0;34m(fname, arr, vmin, vmax, cmap, format, origin, dpi, metadata, pil_kwargs)[0m
[1;32m   1614[0m         [0mpil_kwargs[0m[0;34m.[0m[0msetdefault[0m[0;34m([0m[0;34m"format"[0m[0;34m,[0m [0mformat[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1615[0m         [0mpil_kwargs[0m[0;34m.[0m[0msetdefault[0m[0;34m([0m[0;34m"dpi"[0m[0;34m,[0m [0;34m([0m[0mdpi[0m[0;34m,[0m [0mdpi[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1616[0;31m         [0mimage[0m[0;34m.[0m[0msave[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0;34m**[0m[0mpil_kwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1617[0m [0;34m[0m[0m
[1;32m   1618[0m [0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/icesat2_book/lib/python3.8/site-packages/PIL/Image.py[0m in [0;36msave[0;34m(self, fp, format, **params)[0m
[1;32m   2230[0m                 [0mfp[0m [0;34m=[0m [0mbuiltins[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0;34m"r+b"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2231[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2232[0;31m                 [0mfp[0m [0;34m=[0m [0mbuiltins[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0;34m"w+b"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2233[0m [0;34m[0m[0m
[1;32m   2234[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: './figs/maps_out.png'
FileNotFoundError: [Errno 2] No such file or directory: './figs/maps_out.png'

