Traceback (most recent call last):
  File "/Users/nicolekeeney/opt/anaconda3/envs/is2-book-env/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/nicolekeeney/opt/anaconda3/envs/is2-book-env/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/nicolekeeney/opt/anaconda3/envs/is2-book-env/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/nicolekeeney/opt/anaconda3/envs/is2-book-env/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/nicolekeeney/opt/anaconda3/envs/is2-book-env/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/nicolekeeney/opt/anaconda3/envs/is2-book-env/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/nicolekeeney/opt/anaconda3/envs/is2-book-env/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/nicolekeeney/opt/anaconda3/envs/is2-book-env/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plotMeans(PIO = PIO.sel(time = slice('Nov 2019','Apr 2020')), IS2 = IS2.sel(time = winter_19_20))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-16-a18a515512aa>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mplotMeans[0m[0;34m([0m[0mPIO[0m [0;34m=[0m [0mPIO[0m[0;34m.[0m[0msel[0m[0;34m([0m[0mtime[0m [0;34m=[0m [0mslice[0m[0;34m([0m[0;34m'Nov 2019'[0m[0;34m,[0m[0;34m'Apr 2020'[0m[0;34m)[0m[0;34m)[0m[0;34m,[0m [0mIS2[0m [0;34m=[0m [0mIS2[0m[0;34m.[0m[0msel[0m[0;34m([0m[0mtime[0m [0;34m=[0m [0mwinter_19_20[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'winter_19_20' is not defined
NameError: name 'winter_19_20' is not defined

